apiVersion: apps/v1
kind: Deployment
metadata:
  name: flipkart-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flipkart
  template:
    metadata:
      labels:
        app: flipkart
    spec:
      containers:
        - name: flipkart-container
          image: flipkartapp.azurecr.io/flipkartapp:latest
          ports:
            - containerPort: 8080
